FROM node:14.2.0-alpine3.10

#maybe will need to change to string
WORKDIR /app

COPY package*.json ./

RUN npm install
RUN npm i -g react-scripts
RUN npm i axios --save

COPY . .

CMD ["npm", "run", "start"]
